apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-all.yml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: chat-ui
  name: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-all.yml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/ant-chat: "true"
        io.kompose.service: chat-ui
    spec:
      containers:
        - image: mrangerran/chat-ui:1.0.4
          name: chat-ui
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
