apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --file .\docker-compose-all.yml
    kompose.version: 1.29.0 (997957870)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c --file .\docker-compose-all.yml
        kompose.version: 1.29.0 (997957870)
      creationTimestamp: null
      labels:
        io.kompose.network/ant-chat: "true"
        io.kompose.service: schema-registry
    spec:
      enableServiceLinks: false # mandatory if we want to use "schema-registry" as a name
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka-1:29092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8085
          image: confluentinc/cp-schema-registry:latest
          name: schema-registry
          ports:
            - containerPort: 8085
          resources: {}
      hostname: schema-registry
      restartPolicy: Always
status: {}
